# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent_service.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'agent_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61gent_service.proto\x12\x0b\x61\x65os.agents\"i\n\x13GeneratePlanRequest\x12\x13\n\x0bincident_id\x18\x01 \x01(\t\x12\x10\n\x08severity\x18\x02 \x01(\t\x12\x16\n\x0eroot_signature\x18\x03 \x01(\t\x12\x13\n\x0bworkflow_id\x18\x04 \x01(\t\"L\n\x14GeneratePlanResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x0bworkflow_id\x18\x03 \x01(\t\"\xdc\x01\n\x10SaveAuditRequest\x12\x12\n\nevent_type\x18\x01 \x01(\t\x12\x16\n\x0e\x61gent_identity\x18\x02 \x01(\t\x12\x1a\n\x12\x61\x63tion_description\x18\x03 \x01(\t\x12\x13\n\x0binputs_json\x18\x04 \x01(\t\x12\x14\n\x0coutputs_json\x18\x05 \x01(\t\x12\x13\n\x0bincident_id\x18\x06 \x01(\t\x12\x13\n\x0bworkflow_id\x18\x07 \x01(\t\x12\x12\n\nrisk_score\x18\x08 \x01(\x01\x12\x17\n\x0fprev_entry_hash\x18\t \x01(\t\"4\n\x11SaveAuditResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2e\n\x0ePlannerService\x12S\n\x0cGeneratePlan\x12 .aeos.agents.GeneratePlanRequest\x1a!.aeos.agents.GeneratePlanResponse2[\n\rMemoryService\x12J\n\tSaveAudit\x12\x1d.aeos.agents.SaveAuditRequest\x1a\x1e.aeos.agents.SaveAuditResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEPLANREQUEST']._serialized_start=36
  _globals['_GENERATEPLANREQUEST']._serialized_end=141
  _globals['_GENERATEPLANRESPONSE']._serialized_start=143
  _globals['_GENERATEPLANRESPONSE']._serialized_end=219
  _globals['_SAVEAUDITREQUEST']._serialized_start=222
  _globals['_SAVEAUDITREQUEST']._serialized_end=442
  _globals['_SAVEAUDITRESPONSE']._serialized_start=444
  _globals['_SAVEAUDITRESPONSE']._serialized_end=496
  _globals['_PLANNERSERVICE']._serialized_start=498
  _globals['_PLANNERSERVICE']._serialized_end=599
  _globals['_MEMORYSERVICE']._serialized_start=601
  _globals['_MEMORYSERVICE']._serialized_end=692
# @@protoc_insertion_point(module_scope)
