# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_service_pb2 as agent__service__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlannerServiceStub:
    """The Planner Service handles generating workflows from incident analysis.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GeneratePlan = channel.unary_unary(
                '/aeos.agents.PlannerService/GeneratePlan',
                request_serializer=agent__service__pb2.GeneratePlanRequest.SerializeToString,
                response_deserializer=agent__service__pb2.GeneratePlanResponse.FromString,
                _registered_method=True)


class PlannerServiceServicer:
    """The Planner Service handles generating workflows from incident analysis.
    """

    def GeneratePlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlannerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GeneratePlan': grpc.unary_unary_rpc_method_handler(
                    servicer.GeneratePlan,
                    request_deserializer=agent__service__pb2.GeneratePlanRequest.FromString,
                    response_serializer=agent__service__pb2.GeneratePlanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aeos.agents.PlannerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aeos.agents.PlannerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlannerService:
    """The Planner Service handles generating workflows from incident analysis.
    """

    @staticmethod
    def GeneratePlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aeos.agents.PlannerService/GeneratePlan',
            agent__service__pb2.GeneratePlanRequest.SerializeToString,
            agent__service__pb2.GeneratePlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MemoryServiceStub:
    """The Memory Service handles persistent knowledge and audit logging.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveAudit = channel.unary_unary(
                '/aeos.agents.MemoryService/SaveAudit',
                request_serializer=agent__service__pb2.SaveAuditRequest.SerializeToString,
                response_deserializer=agent__service__pb2.SaveAuditResponse.FromString,
                _registered_method=True)


class MemoryServiceServicer:
    """The Memory Service handles persistent knowledge and audit logging.
    """

    def SaveAudit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveAudit': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveAudit,
                    request_deserializer=agent__service__pb2.SaveAuditRequest.FromString,
                    response_serializer=agent__service__pb2.SaveAuditResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aeos.agents.MemoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aeos.agents.MemoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryService:
    """The Memory Service handles persistent knowledge and audit logging.
    """

    @staticmethod
    def SaveAudit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aeos.agents.MemoryService/SaveAudit',
            agent__service__pb2.SaveAuditRequest.SerializeToString,
            agent__service__pb2.SaveAuditResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
