apiVersion: v1
kind: Secret
metadata:
  name: aeos-secrets
  labels:
    app: aeos-secrets
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
